apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: cinevision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: rootuser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: rootpass
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: cinevision
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP
