apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: cinevision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: cinevision/email-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: cinevision
spec:
  selector:
    app: email-service
  ports:
    - port: 8084
      targetPort: 8084
      name: http
  type: ClusterIP
