apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: cinevision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: cinevision/eureka-server:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: SERVER_PORT
              value: "8761"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: cinevision
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
      name: http
  type: ClusterIP
