apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cinevision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cinevision/frontend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE
              value: "http://api-gateway:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cinevision
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      name: http
  type: NodePort
