apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: cinevision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: cinevision/user-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: cinevision
spec:
  selector:
    app: user-service
  ports:
    - port: 8083
      targetPort: 8083
      name: http
  type: ClusterIP
