name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Maven test
        run: mvn -B -ntp test

      - name: Maven package (skip tests)
        run: mvn -B -ntp -DskipTests package

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci --no-audit --prefer-offline --legacy-peer-deps

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-build
          path: frontend/build
          if-no-files-found: warn

      - name: Upload Maven packages
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: java-targets
          path: |
            **/target/*.jar
            **/target/*.war
          if-no-files-found: warn
